- name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: index.html
          remote: /home/stas/index.html
          host: 176.241.137.19
          port: 48912
          username: stas
          password: e2D0rado
